tugas1/news/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index),
]

tugas1/testimoni/urls.py
from django.urls import path
from .views import index, add_testimoni, get_name

app_name = 'testimoni'

urlpatterns = [
    path('', index, name='index'),
    path('add-testimoni', add_testimoni, name='add-testimoni'),
    path('get-name', get_name, name='get-name'),
]

tugas1/tugas1/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from donate.views import list_donation, get_list_donation
import silverlight

urlpatterns = [
    path('', include('silverlight.urls')),
    path('home/', include('silverlight.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('be-a-donator/', include('donate.urls')),
    path('list-donation/', list_donation, name='list_donation'),
    path('get-list-donation/', get_list_donation, name='get_list_donation'),
    path('test/', silverlight.views.testajax, name='testajax'),
    path('news/', include('news.urls')),
    path('program/', include('program.urls')),
    path('profile/', include('user_profile.urls')),
    path('logout/', views.LogoutView.as_view(next_page='/home/'), name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
    path('testimoni/', include('testimoni.urls', namespace='testimoni')),
]

tugas1/testimoni/models.py
from django.core.validators import MaxLengthValidator
from django.db import models


# Create your models here.

class Testimoni(models.Model):
    testimoni = models.CharField(max_length=300, validators=[MaxLengthValidator(300)])
    created_by = models.ForeignKey('donate.UserModel', related_name='testimoni', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

tugas1/testimoni/forms.py
from django import forms
from .models import Testimoni

class TestimoniForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TestimoniForm, self).__init__(*args, **kwargs)

        self.fields['testimoni'].label = 'Testimoni'
        self.fields['testimoni'].widget = forms.Textarea(attrs={'class': 'form-control',
                                                             'placeholder': 'Apa yang anda rasakan?',
                                                             'rows': 6,
                                                             'cols': 7,
                                                             'style': 'resize : none'}
                                                      )
        self.fields['testimoni'].error_messages = {'max_length': 'Maksimal 300 karakter :(',
                                                'required': 'Mohon mengisi testimoni'}

    class Meta:
        model = Testimoni
        fields = ['testimoni']

tugas1/testimoni/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .forms import TestimoniForm
from .models import Testimoni
from donate.models import UserModel
# Create your views here.

def index(request):
    testimoni = Testimoni.objects.all()
    form = TestimoniForm()
    html = 'testimoni.html'
    return render(request, html, {'status': testimoni, 'form': form})


def add_testimoni(request):
    if request.method == 'POST':
        print(request.POST)
        form = TestimoniForm(request.POST)
        if form.is_valid():
            testimoni = form.save(commit=False)
            user = UserModel.objects.get(email=request.session['email'])
            testimoni.created_by = user
            testimoni.save()
            return HttpResponseRedirect(reverse('testimoni:index'))
    else:
        form = TestimoniForm()

    return render(request, 'testimoni.html', {'status' : Testimoni.objects.all(), 'form' : form})


def get_name(request):
    name = Testimoni.objects.all()
    name_list = [{'id': obj.id, 'name': obj.name, 'email': obj.email}
                        for obj in subscribers]
    return HttpResponse(json.dumps({'subscribers': name_list}),
                        content_type='application/json')

tugas1/testimoni/templates/testimoni.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="mymain">
    <div class="content">
        <p>
            A nonprofit crowdfunding organization
        </p>
    </div>

    <div class="jumbotron">
        <div class="container-fluid">
            <h1 class="page-header" style="text-align: center">About SinarPerak</h1>
            <p><b>SinarPerak adalah organisasi yang bergerak untuk mengumpulkan <br>
            dana dan disalurkan kepada mereka yang membutuhkan</b></p>
        </div>
    </div>

    <div class="container mx-auto d-block" style="padding-top: 50px;">
        {% if status %}
            <table class="table table-hover table-striped table-dark" allign="center" style="text-align: center" id="testimoni-table">
                <thead>
                    <tr>
                        <th scope="col">Testimoni</th>
                        <th scope="col">Waktu</th>
                        <th scope="col">Nama</th>
                    </tr>
                </thead>
                {% for data in status %}
                <tr>
                    <td scope="row">{{ data.testimoni }}</td>
                    <td scope="row">{{ data.created_at|date:"l" }}, {{ data.created_at }}</td>
                    <td scope="row">{{ request.session.display_name }}</td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <h1 class="text-main">Yuk, katakan sesuatu tentang kami!</h1>
        {% endif %}
    </div>


    <div class="container mx-auto d-block">
        {% if user.is_authenticated %}
        <form class="form-block" action="{% url 'testimoni:add-testimoni' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{ form }}
            </div>
            <button type="submit" id="input_button" class="btn btn-primary">Berikan Testimoni!</button>
        </form>
        {% endif %}
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function()){
        $('#testimoni-table').DataTable({
            ajax : {
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                url: "{% url 'testimoni:get-name' %}",
                dataSrc: 'subscribers',
            }
        })
    }

    $('#subscriber-table').on('click', 'td .unsubscribe', function () {
                var subscriberId = $(this).attr('data-id');
                $.ajax({
                    url: unsubscribeURL,
                    method: 'POST',
                    type: 'json',
                    data: {'subscriber_id': subscriberId},
                }).then(function () {
                   $('#subscriber-table').DataTable().ajax.reload();
                });
            });

</script>
{% endblock %}